### ISSUE TITLE
Markdown parser issue

### ISSUE THREAD

**Issue by gordonbazeley** [rberenguel/bear-note-graph#2]
Thanks for 0.1.2 - I've just upgraded and am now getting the following error:

Traceback (most recent call last):
  File "/usr/local/bin/bear-note-graph", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bear_note_graph/main.py", line 122, in main
    generate_graph(graph_format)
  File "/usr/local/lib/python3.7/site-packages/bear_note_graph/generate.py", line 61, in generate_graph
    blocks, _ = MARKDOWN_PARSER.parse(md_text)
  File "/usr/local/lib/python3.7/site-packages/bear_note_graph/parser.py", line 332, in parse
    raise Exception(err)
Exception: No parser can process <<[

**Comment by rberenguel** [comment]
Hi @gordonbazeley thanks for using and reporting it.

This is very likely an issue with an open bracket followed by nothing, it should be captured by the fallback parser. I was able to reproduce with a note with

```
# aaa
[

duh
```

Will fix it later today (I also found that it chokes on empty notes, which can happen relatively often).

I'll ping you when I fix the issue, for now... if you could find the problematic note it would fix it. For the new version I will add logging of the note name here, which should make fixing or finding problematic notes easier

**Comment by rberenguel** [comment]
@gordonbazeley this should be fixed in version 0.1.4, an empty bracket is no longer a reason for parsing to fail. Also now if the parser fails for some reason, it will report which note had the problem too

**Comment by rberenguel** [comment]
I'll close the issue for now, if it happens again please reopen and I'll dig deeper
